[workspace]
resolver = "2"
members = [
    "keysas-core/",
    "keysas-io/",
    "keysas-backend/",
    "keysas-sign/",
    "keysas-fido/",
    "keysas_lib/",
    "keysas-admin/src-tauri",
]

exclude = [
    "keysas-firewall"
]
