[package]
name = "keysas-admin"
version = "0.1.2"
description = "Keysas stations administration application"
authors = ["Stephane N", "Luc Bonnafoux"]
license = "GPL-3.0"
repository = ""
default-run = "keysas-admin"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.3", features = ["api-all", "updater"] }
ssh-rs = "0.3.2" 
tauri-plugin-store = { git="https://github.com/r3dlight/tauri-plugin-store", branch="dev" }
anyhow ="*"
async-std = "*"
nom = "*"
sha2 ="*"
regex="*"
openssl = "*"
openssl-sys = "*"
sqlite = "*"
simple_logger = "*"
log = "*"
pkcs8 = {version = "*", features = ["encryption", "pem"] }
x509-cert = "*"
arbitrary = "*"
ed25519-dalek = "1"
rand = "0.7.0"
oqs = "*"
hex-literal = "*"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
