[package]
name = "keysas_lib"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "*"
anyhow = "*"
clap = "*"
walkdir ="*"
regex ="1.7.1"
simple_logger = "4.1"
log = "0.4"
pkcs8 = {version = "0.10", default-features = false, features = ["encryption", "pem"] }
x509-cert = "0.2"
arbitrary = "1.3"
ed25519-dalek = "1"
rand_dl = {package = "rand", version = "0.7"}
rand_core = "0.6.4"
oqs = "0.7"
hex-literal = "0.3"
tempdir = "*"