name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: |
        sudo apt-get update -yq
        sudo apt -y install \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libyara-dev \
          libyara9 \
          make \
          lsb-release \
          software-properties-common \
          libseccomp-dev \
          pkg-config \
          git \
          bash \
          libudev-dev \
          cmake \
          libsoup2.4-dev \
          libjavascriptcoregtk-4.0-dev \
          libwebkit2gtk-4.0-dev
    - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Build
      run: cargo build --verbose
    - name: Run audit
      run: |
        cargo install cargo-audit
        cargo audit
